### ISSUE TITLE
feature: Clarify what is supported

### ISSUE THREAD

**Issue by meedstrom** [tree-sitter-grammars/tree-sitter-svelte#11]
### Did you check the tree-sitter docs?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

I am attempting to make an Emacs mode that uses this grammar. I am new to tree-sitter, so I'm just learning as I go. 

Anyway, Emacs has a `treesit-inspect-mode` to show me what node is under the cursor.  So I move the cursor to the code between <script> tags and it seems that...this grammar doesn't ship rules for JS/TS? It's all the same node type: `(script_element (raw_text))`.

Am I to understand that I am meant to combine this grammar with external CSS/TS grammars?

### Describe the solution you'd like

Perhaps a short README section to clarify what it does and does not do.

While we're at it, clarifying whether it supports Svelte 5 would be good too.

**Comment by clason** [comment]
> Am I to understand that I am meant to combine this grammar with external CSS/TS grammars?


Yes, that is how tree-sitter works. Use injections queries to parse contents of nodes as other languages (see nvim-treesitter for examples).
