### ISSUE TITLE
discussion - svelte + ast-grep

### ISSUE THREAD

**Issue by alexbit-codemod** [tree-sitter-grammars/tree-sitter-svelte#7]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

there is no good solution out there for automated transformation for svelte.

### Describe the solution you'd like

update tree-sitter-svelte parser and have it integrated with ast-grep.

### Describe alternatives you've considered

n/a

### Additional context

in the founder of Codemod. would love to chat and explore a partnership to integrate your awesome parser with ast-grep. this will add a huge impact to the community. feel free to book me to chat more: https://cal.com/alexbit/15min

**Comment by clason** [comment]
No thank you. Feel free to use the parser under the provided license (and if there's a standard binding from `tree-sitter generate` missing, open a PR).
